const Menu = [
  {
    id: 1,
    Image: "https://i.postimg.cc/dQmMq2xS/Mega-Shield.png",
    title: "Electrical for Robotic Hand ",
    category: "Integration",
    link: "projects/robotic-hand",
  },
  {
    id: 2,
    Image: "https://i.postimg.cc/TwDmXY2n/Voron.png",
    title: "FDM 3D Printer",
    category: "Integration",
    link: "projects/voron",
  },
  {
    id: 3,
    Image: "https://i.postimg.cc/tJy4sXy0/Vanagon.png",
    title: "Vanagon CAN Emulation",
    category: "Integration",
    link: "projects/can-emulation",
  },
  {
    id: 4,
    Image: "https://i.postimg.cc/Gm2189NC/Eigenfaces.jpg",
    title: "Facial Recognition",
    category: "Software",
    link: "projects/facial-recognition",
  },
  {
    id: 5,
    Image: "https://i.postimg.cc/C5HpXDWX/Kinova.png",
    title: "6-DOF Kinematics",
    category: "Robotics",
    link: "projects/kinova-kinematics",
  },
  {
    id: 6,
    Image: "https://i.postimg.cc/7YSVbk9B/gaussian-foot.jpg",
    title: "3D Gaussian Splatting",
    category: "Software",
    link: "projects/gaussian-splatting",
  },
  {
    id: 7,
    Image: "https://i.postimg.cc/J4G87DCw/AgDrone.png",
    title: "Drone Perception & Navigation",
    category: "Robotics",
    link: "projects/drone-perc-nav",
  },
  {
    id: 8,
    Image: "https://i.postimg.cc/L6mSSx3h/AirPong.jpg",
    title: "Video Game: Air Pong",
    category: "Software",
    link: "https://olincollege.github.io/air-pong/",
  },
  {
    id: 9,
    Image: "https://i.postimg.cc/fykGZFZq/cv2output_first_success.jpg",
    title: "[IP] Software For Swarm Robot Chair & Trashcan",
    category: "Robotics",
    link: "projects/desk-on-demand",
  },
  {
    id: 10,
    Image: "https://i.postimg.cc/xd38bkmL/camera-calib.jpg",
    title: "[IP] Guassian Splatting for 3D Reconstruction",
    category: "Robotics",
    link: "projects/gaussian-guy",
  },
];
export default Menu;
